export const servers = [
  "Alice",
  "Byakuren",
  "Chen",
  "Cirno",
  "Clownpiece",
  "Doremy",
  "Flandre",
  "Hong Meiling (Chinese Girl)",
  "Koishi",
  "Komachi",
  "Marisa",
  "Mokou",
  "Nue (SOMEBODY SCREAM)",
  "Reimu (Hitbox)",
  "Reisen (Raisin)",
  "Remilia",
  "Rumia",
  "Sakuya (Knives)",
  "Satori",
  "Suwako",
  "Tenshi",
  "Utsuho",
  "Yoshika",
  "Youmu",
  "Yuyuko",
];

export const helpMessage = [
  "Global Commands",
  "-help - To view all commands",
  "",
  "Room Commands",
  "-save [Setup Name] - Save room setup",
  "-load (Setup Name / ID) - Load a room setup",
  "-leave - Makes the bot leave the room",
].join("\n");
