export const servers = [
  "Alice",
  "Byakuren",
  "Chen",
  "Cirno",
  "Clownpiece",
  "Doremy",
  "Flandre",
  "Hong Meiling (Chinese Girl)",
  "Koishi",
  "Komachi",
  "Marisa",
  "Mokou",
  "Nue (SOMEBODY SCREAM)",
  "Reimu (Hitbox)",
  "Reisen (Raisin)",
  "Remilia",
  "Rumia",
  "Sakuya (Knives)",
  "Satori",
  "Suwako",
  "Tenshi",
  "Utsuho",
  "Yoshika",
  "Youmu",
  "Yuyuko",
];

export const helpMessage =
  "Hello, I am Setup! The bot to load and save room setups! To view my commands and how to use me, go to https://sf-hub.cc/setup";
